name: $(Build.BuildID)

pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: PowerShell@2
    name: 'set docker tag and pipeline tag'
    inputs:
      targetType: "inline"
      script: |
        if(!("$(Build.Reason)".Equals("PullRequest"))){
          Write-Host "##vso[task.setvariable variable=BuildVersioning]$(Build.BuildID)"
          Write-Host "##vso[task.setvariable variable=IsLatest]latest"
          Write-Host "Masterversion: $(Build.BuildID)"
        } else {
          Write-Host "##vso[task.setvariable variable=BuildVersioning]dev-$(System.PullRequest.PullRequestNumber)"
          Write-Host "##vso[task.setvariable variable=IsLatest]"
          Write-Host "PR-Version: dev-$(System.PullRequest.PullRequestNumber)"
          Write-Host $(System.PullRequest.SourceBranch)
          if("$(System.PullRequest.SourceBranch)".StartsWith("DEPLOY_")) {
            az pipelines build tag add --build-id $(Build.BuildID) --tags pr-deployment
          }
        }

  - task: Docker@2
    inputs:
      containerRegistry: "official-docker-modmoto"
      repository: "modmoto/w3champions-ui"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      buildContext: "."
      tags: |
        $(BuildVersioning)
        $(IsLatest)

  - task: CopyFiles@2
    name: 'publish docker-compose files'
    inputs:
      contents: '**/*docker-compose.yml'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
