name: $(Build.BuildID)

pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        if(!("$(Build.Reason)".Equals("PullRequest"))){
          Write-Host "##vso[task.setvariable variable=BuildVersioning]$(Build.BuildID)"
          Write-Host "##vso[task.setvariable variable=IsLatest]latest"
          Write-Host "Masterversion: $(Build.BuildID)"
        } else {
          Write-Host "##vso[task.setvariable variable=BuildVersioning]dev-$(System.PullRequest.PullRequestNumber)"
          Write-Host "##vso[task.setvariable variable=IsLatest]"
          Write-Host "PR-Version: dev-$(System.PullRequest.PullRequestNumber)"
          dir
          if(Test-Path('pull-request-docker-compose.yml')) {
            az pipelines build tag add --tags pr-deployment
          }
        }

  - task: Docker@2
    inputs:
      containerRegistry: "official-docker-modmoto"
      repository: "modmoto/w3champions-ui"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      buildContext: "."
      tags: |
        $(BuildVersioning)
        $(IsLatest)
