version: '3.1'
services:
  w3champions-ui-dev:
    image: modmoto/w3champions-ui:#{TAG}#
    container_name: w3champions-ui-pr-#{PR_NAME}#
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=pr-#{PR_NAME}#.ui.w3champions.com
      - LETSENCRYPT_HOST=pr-#{PR_NAME}#.ui.w3champions.com
      - LETSENCRYPT_EMAIL=simonheiss87@gmail.com
      - BASE_URL=https://statistic-service.test.w3champions.com/
      - IDENTIFICATION_URL=https://identification-service.test.w3champions.com/
      - FEATURE_FLAG_CLANS=true
      - TAG=latest
      - LAUNCHER_UPDATE_URL=https://update-service.test.w3champions.com/api/
      - INGAME_STATIC_RESOURCES_URL=https://w3champions.wc3.tools/test/integration/
      - BNET_API_CLIENT_ID=d7bd6dd46e2842c8a680866759ad34c2
      - S3_ACESS_KEY=E7K3YD3GYWUHIIC6DWJ9
      - S3_SECRET_KEY=ABZP9QNRxU9pb2NoyFFi1D4SdSWoSrPbKAdbXilI
      - STAGE=dev
      - SITE_CDN_URL=https://w3champions.wc3.tools/test/site

networks:
  default:
    external:
      name: nginx-proxy
